apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      initContainers:
      - name: wait-frontend
        image: alpine:3.7
        command: ['sh', '-c']
        args: ['echo -e "http://nl.alpinelinux.org/alpine/v3.5/main\nhttp://nl.alpinelinux.org/alpine/v3.5/community" > /etc/apk/repositories;
            apk update;
            apk add curl;
            until curl -f -m 2 -s -S "${FRONTEND_ADDR}" > /dev/null; do
              echo "waiting for ${FRONTEND_ADDR}";
              sleep 2;
            done;
            echo "Reached ${FRONTEND_ADDR}."']
        env:
        - name: FRONTEND_ADDR
          value: "http://istio-ingressgateway.istio-system"
      containers:
      - name: main
        image: djmcaleese/acmefitness-loadgen:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8089
        env:
        - name: FRONTEND_ADDR
          value: "http://istio-ingressgateway.istio-system"
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
